### ISSUE TITLE
Setting up doozer.

### ISSUE THREAD

**Issue by AraHaan** [AraHaan/bin2c#3]
For my bin2c conversion tool I need to somehow set up doozer much like I have travis set up and I need to figure out how to make it build for the OSX as well in both 32 and 64 bit on both Ubuntu trusty and on OSX.

@nmred you happen to know how I can set this up and also set it to latest gcc and clang with separate builds per compiler to build?

**Comment by nmred** [comment]
@AraHaan you need create .doozer.json config

doozer document https://doozer.io/docs/doozerjson

you can refer my project doozer.json https://github.com/weiboad/adbase/blob/master/.doozer.json

**Comment by nmred** [comment]
if you need lastest gcc and clang ,you can apt-get newer

**Comment by AraHaan** [comment]
ok, thanks and yeah I am thinking about dropping travis for doozer as there is too much hackery involded with it and it currenly has 64 bit builds while doozer seems to have both 32 and 64 bit ones.

**Comment by AraHaan** [comment]
ok, I got some of it setup just on the OSX I got to figure out on the getting homebrew to work for the latest gcc and or clang it has.

**Comment by AraHaan** [comment]
I just found an short hack to get the version of gcc and clang people want to use.

https://github.com/tonykero/Moe/blob/master/.travis.yml

Hope this can help other C++ 14 projects out a lot too. Expecially the ones that use the filesystem TS.

**Comment by AraHaan** [comment]
Ok, I finnally got 2 of the builds to finish successfully. However I need to get the other 4 to work right.

**Comment by AraHaan** [comment]
@nmred Well I am having issues with getting Doozer to install clang 3.9 on some of the builds.

**Comment by AraHaan** [comment]
Ok so I think I got it mostly setup on terms of linux. However on OSX it is pretty much no dice.

**Comment by AraHaan** [comment]
I have dropped OSX for now until I figure out how to fix OSX to work with the ``<experimental/filesystem>`` header.

**Comment by AraHaan** [comment]
Seems that Homebrew has the issue on the reason why <experimental/filesystem> is not present on it.

see https://github.com/Homebrew/homebrew-core/pull/10778 for details.

For now I have to reopen this until that is merged and then I can reenable OSX on Doozer.

**Comment by AraHaan** [comment]
I decided to move from Travis and Doozer.io to github actions.
