### ISSUE TITLE
Move to cmake.

### ISSUE THREAD

**Issue by AraHaan** [AraHaan/bin2c#4]
I think it would be better to move all the setup to cmake.

**Comment by cemysf** [comment]
could you explain how do you compile it on linux?

**Comment by AraHaan** [comment]
Well that is a manual g++/clang++ invocation. Which is another reason why I would like to get cmake setup and set to the c++17 standard (and to link to the needed libraries like ``-lstdc++fs`` on gcc/g++, and ``-lc++ -lc++experimental`` on clang. The Doozer.json file also has the commands used on it too.

**Comment by Montx** [comment]
I have some experience with cmake, I don't mind helping you out.

**Comment by AraHaan** [comment]
ok, thanks.
